default: &default
  adapter: postgresql
  encoding: unicode
  username: jmowrey27
  password: '#93Engineer'
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: projectapp_database

test:
  <<: *default
  database: projectapp_test_database

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
